# projects.toml file describing inputs for dream2nix
#
# To re-generate this file, run:
#   nix run .#detect-projects $source
# ... where `$source` points to the source of your project.
#
# If the local flake is unavailable, alternatively execute the app from the
# upstream dream2nix flake:
#   nix run github:nix-community/dream2nix#detect-projects $source

[sdc-map-frontend]
name = "sdc-map-frontend"
relPath = ""
subsystem = "nodejs"
translator = "yarn-lock"
translators = ["yarn-lock", "package-json"]

[tweetnacl]
name = "tweetnacl"
relPath = "node_modules/tweetnacl"
subsystem = "nodejs"
translator = "package-json"
translators = ["package-json"]

[tweetnacl-util]
name = "tweetnacl-util"
relPath = "node_modules/tweetnacl-util"
subsystem = "nodejs"
translator = "package-json"
translators = ["package-json"]

[sdc-map-frontend.subsystemInfo]

[tweetnacl.subsystemInfo]

[tweetnacl-util.subsystemInfo]
