[package]
name = "sdc-map-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["headers"] }
hyper = "0.14.26"
lazy_static = "1.4.0"
serde = { version = "1.0.163", features = ["derive"] }
sqlite = "0.30.4"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.4.0", features = ["fs"] }
