module Evergreen.Migrate.V2 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Types
import Evergreen.V2.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V2.Types.FrontendModel Evergreen.V2.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V2.Types.BackendModel Evergreen.V2.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V2.Types.FrontendMsg Evergreen.V2.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V2.Types.ToBackend Evergreen.V2.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V2.Types.BackendMsg Evergreen.V2.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V2.Types.ToFrontend Evergreen.V2.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_EncryptedString : Evergreen.V1.Types.EncryptedString -> Evergreen.V2.Types.EncryptedString
migrate_Types_EncryptedString old =
    case old of
        Evergreen.V1.Types.EncryptedString p0 ->
            Evergreen.V2.Types.EncryptedString p0


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V2.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.Name p0 ->
            Evergreen.V2.Types.Name p0

        Evergreen.V1.Types.Country p0 ->
            Evergreen.V2.Types.Country p0

        Evergreen.V1.Types.Location p0 ->
            Evergreen.V2.Types.Location p0

        Evergreen.V1.Types.NameOnMap p0 ->
            Evergreen.V2.Types.NameOnMap p0

        Evergreen.V1.Types.Id p0 ->
            Evergreen.V2.Types.Id p0

        Evergreen.V1.Types.Captcha p0 ->
            Evergreen.V2.Types.Captcha p0

        Evergreen.V1.Types.Submit ->
            Evergreen.V2.Types.Submit

        Evergreen.V1.Types.Encrypted p0 ->
            Evergreen.V2.Types.Encrypted (p0 |> migrate_Types_EncryptedString)

        Evergreen.V1.Types.Dumped p0 ->
            Evergreen.V2.Types.Nop

        Evergreen.V1.Types.AdminSecretKey p0 ->
            Evergreen.V2.Types.AdminSecretKey p0

        Evergreen.V1.Types.Decrypt ->
            Evergreen.V2.Types.Decrypt

        Evergreen.V1.Types.Decrypted p0 ->
            Evergreen.V2.Types.Decrypted p0

        Evergreen.V1.Types.Nop ->
            Evergreen.V2.Types.Nop


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V2.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.TBSubmit p0 ->
            Evergreen.V2.Types.TBSubmit (p0 |> migrate_Types_EncryptedString)


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V2.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.TFSubmitted p0 ->
            Evergreen.V2.Types.TFSubmitted p0
