module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V2.Types
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import Set


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_EncryptedString : Evergreen.V2.Types.EncryptedString -> Evergreen.V4.Types.EncryptedString
migrate_Types_EncryptedString old =
    case old of
        Evergreen.V2.Types.EncryptedString p0 ->
            Evergreen.V4.Types.EncryptedString p0


migrate_Types_FrontendModel : Evergreen.V2.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    case old of
        Evergreen.V2.Types.Filling p0 p1 ->
            Evergreen.V4.Types.Filling (p0 |> migrate_Types_Input) p1

        Evergreen.V2.Types.Encrypting p0 ->
            Evergreen.V4.Types.Encrypting (p0 |> migrate_Types_Input)

        Evergreen.V2.Types.Submitting p0 ->
            Evergreen.V4.Types.Submitting (p0 |> migrate_Types_Input)

        Evergreen.V2.Types.Submitted p0 ->
            Evergreen.V4.Types.Submitted
                { id = p0.id
                , input = p0.input |> migrate_Types_Input
                }

        Evergreen.V2.Types.AdminDecrypting p0 p1 ->
            Evergreen.V4.Types.AdminDecrypting p0
                (p1 |> Dict.map (\k -> migrate_Types_EncryptedString))

        Evergreen.V2.Types.AdminDecrypted p0 ->
            Evergreen.V4.Types.AdminDecrypted Set.empty (p0 |> List.map migrate_Types_Input)


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V2.Types.Name p0 ->
            Evergreen.V4.Types.Name p0

        Evergreen.V2.Types.Country p0 ->
            Evergreen.V4.Types.Country p0

        Evergreen.V2.Types.Location p0 ->
            Evergreen.V4.Types.Location p0

        Evergreen.V2.Types.NameOnMap p0 ->
            Evergreen.V4.Types.NameOnMap p0

        Evergreen.V2.Types.Id p0 ->
            Evergreen.V4.Types.Id p0

        Evergreen.V2.Types.Captcha p0 ->
            Evergreen.V4.Types.Captcha p0

        Evergreen.V2.Types.Submit ->
            Evergreen.V4.Types.Submit

        Evergreen.V2.Types.Encrypted p0 ->
            Evergreen.V4.Types.Encrypted (p0 |> migrate_Types_EncryptedString)

        Evergreen.V2.Types.AdminSecretKey p0 ->
            Evergreen.V4.Types.AdminSecretKey p0

        Evergreen.V2.Types.Decrypt ->
            Evergreen.V4.Types.Decrypt

        Evergreen.V2.Types.Decrypted p0 ->
            Evergreen.V4.Types.Decrypted p0

        Evergreen.V2.Types.Nop ->
            Evergreen.V4.Types.Nop


migrate_Types_Input : Evergreen.V2.Types.Input -> Evergreen.V4.Types.Input
migrate_Types_Input old =
    old
